FROM python:3.11-slim
WORKDIR /app
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt
COPY . .
EXPOSE 8000
CMD ["python", "-c", "print('Docker build environment works fine.')"]
